from typing import Protocol


class Broker(Protocol):
    async def usdt_balance(self) -> float: ...
    async def positions(self) -> list[dict]: ...
    async def place_market(
        self, symbol: str, side: str, qty: float, *, sl: float | None = None, tp: float | None = None
    ) -> dict: ...
    async def close(self) -> None: ...
